DECLARE @DATABASENAME VARCHAR(MAX)
DECLARE @CAMINHO VARCHAR(MAX)
DECLARE @DATA VARCHAR(100)

SET @DATABASENAME = DB_NAME()
SET @CAMINHO = N'C:\SQLServer\BACKUP\'
SET @DATA = REPLACE(CONVERT(VARCHAR(100), GETDATE(), 120), ' ', '_')
SET @DATA = REPLACE(@DATA, ':', '-')

DECLARE @SQLCOMMAND NVARCHAR(MAX) = ''

SET @SQLCOMMAND = 'BACKUP DATABASE ' + QUOTENAME(@DATABASENAME) + ' TO DISK = ''' + @CAMINHO + @DATABASENAME + '_' + @DATA + '.BAK'' WITH COMPRESSION, STATS = 5'

/* Ao descomentar o trecho abaixo, você gera o script para realizar o backup manual! */
--PRINT @SQLCOMMAND

EXEC sp_executesql @SQLCOMMAND